### ISSUE TITLE
GitHub issue 에 소유자 외에 등록 방지하기 (close or delete)

### ISSUE THREAD

**Issue by lepffm** [lepffm/issuance#163]
목적: issue 에 다른 사람이 글을 등록하지 못하도록 차단

- action 생성
- 아래 내용 작성
- setting > action > general > Allow all actions and reusable workflows

1) force close 

```yaml
name: Force close unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.issue.user.login != github.repository_owner
        name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          close-reason: not_planned
          comment: only the owner can post. 
```

2) force delete issue
```yaml
name: Force delete unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - if: github.event.issue.user.login != github.repository_owner
        name: Delete Issue
        run: gh issue delete $NUMBER --yes
        env:
          # 삭제시에는 어드민 권한을 가진 GH TOKEN 을 만들어 secret 에 ISSUE_CLOSE_TOKEN 같은 이름으로 등록 해야함 
          GH_TOKEN: ${{ secrets.ISSUE_CLOSE_TOKEN }} # admin role for delete  
          GH_REPO:  ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
```
