### ISSUE TITLE
Spring Webflux project 에서 로그 추적성 제공하기

### ISSUE THREAD

**Issue by lepffm** [lepffm/issuance#176]
Spring Webflux project 에서 로그 추적성 제공하기

### requirement
- 로그에 추적가능한 id를 남기고 싶다.
- 로그 호출 시 일일이 포함시키지 않고 자동으로 설정되게 하고 싶다.
- MicroService 로 여러 서비스가 연계될때 동일한 식별자로 연결되게 하고 싶다.

### related object
- Spring Boot uses Micrometer Observation
- Facade 역할을 하는 Micrometer 를 이용하여 tracing 구현체에 따라 적용 가능.
- weblfux는 Reactive 수행으로 Thread간 이동이 빈번하여 Tracing Context Propagation 이 필수
- spring actuator 와 결합하여 간단한 설정만으로 기능 제공

### implementation 
build.gradle
```gradle
dependencies {  
    ...  
    implementation org.springframework.boot:spring-boot-starter-actuator  
    // case 1 for  OpenZipkin Brave
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    // case 2 for opentelemetry
    // implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    ...  
}
```
application.yaml
```yaml
spring.reactor.context-propagation: auto # required for context propagation 

logging.pattern.correlation: [%X{traceId:-},%X{spanId:-}]"
or
logging.pattern.level: "%5p [%X{traceId:-},%X{spanId:-}]"
```
or logback-spring.xml
`<pattern>... %X{traceId:-NONE} ... </pattern>`

### example
```java
2024-06-08T20:38:08.217+02:00  INFO [94739f90c9e13ec3a7048d5dfba4c499,61c824a2d63bbe99] 1234 --- [ctor-http-nio-2] lepffm.Service2Controller    : logging...
```
### 남기는 말
갈수록 표준화되고 간단해지는 기술 적용은 좋지만 점점 바보가 되어 가는 느낌도...
servlet project 인 경우 `spring.reactor.context-propagation` 만 제거하면 됨

### reference
https://docs.spring.io/spring-boot/reference/actuator/observability.html
https://docs.spring.io/spring-boot/reference/actuator/tracing.html
https://micrometer.io/docs/tracing
